### ISSUE TITLE
Missing securityContext element in copy-responses containers

### ISSUE THREAD

**Issue by subigre** [wiremock/helm-charts#42]
### Proposal

WireMock deployment failed while using the Helm chart on a cluster with FIPS compliant mode is enabled due to the missing securityContext parameter in `copy-responses` init container:
```yaml
        - name: copy-responses
          image: "{{ .Values.initContainer.image.repository }}:{{ .Values.initContainer.image.tag }}"
          imagePullPolicy: {{ .Values.initContainer.image.pullPolicy }}
          command: ["bash", "-c", "cp  -rf /data/responses /home/wiremock/storage/__files"]
          volumeMounts:
            - mountPath: /data/responses
              name: responses-volume
            - mountPath: /home/wiremock/storage/__files
              name: responses-data
```

### Steps:
1. Set up FIPS compliant mode on the K8s cluster or configure the Pod Security Admission with `baseline` or `restricted`
2. Use `helm install` command as defined in the README.md

### Result:

```
Error creating: pods "wiremock-66c5f5ccd-ndhp2" is forbidden: violates PodSecurity "restricted:latest": allowPrivilegeEscalation != false must set securityContext.allowPrivilegeEscalation = false), ....
```

### References

- https://github.com/subigre/wiremock-helm-charts/blob/master/charts/wiremock/templates/deployment.yaml#L76-L77
