### ISSUE TITLE
How to map with local mappings and response files

### ISSUE THREAD

**Issue by aleproust** [wiremock/helm-charts#56]
### Summary

Hello,
I've been using your chart and I was trying to use files on my local to configure the mappings and response.

I tried to go with volumes
```
volumes:
  - name: mappings-data
    hostPath:
      path: /data/mappings
  - name: responses-data
    hostPath:
      path: /data/responses
volumeMounts:
  - name: mappings-data
    mountPath: /home/wiremock/mappings
  - name: responses-data
    mountPath: /home/wiremock/__files
``` 

or with a command line with --set-file mappings.custom.mapping.json=./mappings/custom_mapping.json

But I'm facing error. Is there any documentation on how to do this? 

Thanks

**Comment by gitkent** [comment]
@aleproust if your mappings and responses files are on your local, please utilise out of the box [mappings](https://github.com/wiremock/helm-charts/tree/master/charts/wiremock/mappings) and [responses](https://github.com/wiremock/helm-charts/tree/master/charts/wiremock/responses) folders.

Thanks

**Comment by aleproust** [comment]
I'm deploying on a kubernetes cluster with the command:

`helm upgrade --install wiremock wiremock/wiremock -n mock`

I wanted to use local files to use them directly into the cluster

Here is my setup of local custom responses:

![Image](https://github.com/user-attachments/assets/80861a55-d126-45ce-8eae-9c7badaeb7b7)

I tried different approach:

1.  Using a command line to override the values file
`  helm upgrade --install wiremock wiremock/wiremock -n mock  --set-file mappings.custom_mapping.json=./mappings/custom_mapping.json --set-file responses.custom_responses.json=./responses/custom_response.json` 

But I get an error 
`json: cannot unmarshal object into Go struct field ConfigMap.data of type string`

2. Volume approach 
`helm upgrade --install wiremock wiremock/wiremock --debug -n mock --values values.yaml`

![Image](https://github.com/user-attachments/assets/963e9c8c-d5de-460f-be88-e4af2992775e)

But no file are mounted in the containers.

I wanted to avoid clone this repository

**Comment by DanielFran** [comment]
@aleproust I never found a good way to do it, you cannot use external directories...

The only solution I found so far is:
- helm pull wiremock --repo https://wiremock.github.io/helm-charts --version 1.5.1 --untar;
- rm -rf ./wiremock/mappings/* && cp ./mappings/*.json ./wiremock/mappings
- rm -rf ./wiremock/responses/* && cp ./responses/*.json ./wiremock/responses
- rm -rf wiremock-1.5.1.tgz
- helm package ./wiremock
- helm upgrade --install wiremock ./wiremock-1.5.1.tgz --debug -n mock --values values.yaml

@gitkent I am open to other suggestions...

**Comment by WesselAtWork** [comment]
You've stumbled on one of helm's oldest idiosyncrasies 

https://github.com/helm/helm/issues/3276

It is buried in their [docs ](https://helm.sh/docs/chart_template_guide/accessing_files/)
> Files outside of a Helm application subchart, including those of the parent, cannot be accessed


Basically you can't add to the `mappings` directory and the `responses` directory from your workspace.

---
@aleproust 
Your invocation of `--set-file` is wrong.

`--set-file=VALUE_PATH=FS_PATH`
so that means your: `mappings.custom.mapping.json` is doing this:
```yaml
mappings:
  custom:  
    mapping:
      json: "<YOUR JSON>"
```

what you want is:
`--set-file="mappings.custom_mapping\.json=mappings/custom_mapping.json"`
 NOTE: the `\.` to escape the `.`

which will result in:
```yaml
mappings:
  mapping.json: "<YOUR JSON>"
```

Which is what you want.


Try it yourself:
`example.json`
```json
{"hello":"world"}
```

`helm template wiremock wiremock/wiremock --set-file 'mappings.myfile\.json=example.json' --debug --dry-run > generated.yaml`

in `generated.yaml` you should see:
```yaml
---
# Source: wiremock/templates/configmap-mappings.yaml
apiVersion: v1
kind: ConfigMap
metadata:
  name: wiremock-mappings-configs
  labels:
    helm.sh/chart: wiremock-1.7.0
    app.kubernetes.io/name: wiremock
    app.kubernetes.io/instance: wiremock
    app.kubernetes.io/version: "3.10.0"
    app.kubernetes.io/managed-by: Helm
data: 
  mapping_1.json: "{\n  \"request\": {\n      \"method\": \"POST\",\n      \"url\": \"/v1/hello\"\n  },\n  \"response\":{\n    \"status\":200,\n    \"bodyFileName\":\"responses/response_1.json\",\n    \"headers\":{\n       \"Content-Type\":\"application/json\"\n    }\n }\n}" 
  myfile.json: '{"hello":"world"}'
---
```

---
@DanielFran 
you can use:
`$(cd local-mappings; printf -v fmt ' --set-file=mappings.%s=local-mappings/%%s' $(echo *.json | sed 's!\.!\\\.!g'); printf "$fmt" *.json)`  
`$(cd local-responses; printf -v fmt ' --set-file=responses.%s=local-responses/%%s' $(echo *.json | sed 's!\.!\\\.!g'); printf "$fmt" *.json)`

If you want to generate the set-file commands for a bare `helm upgrade`
